name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  maven-install:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Build with Maven
        run: mvn --batch-mode -T 1C -U install -Dgpg.skip
