name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  maven-install:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn --batch-mode -T 1C -U install -Dgpg.skip
